version: '3.9'

services:
  postgres:
    image: postgres:16.2-bullseye
    ports:
      - 5432:5432
    volumes:
      - /opt/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${KS_PG_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
